import type { IdeaStockLite } from '@/types';

export const DUMMY_STOCKS: IdeaStockLite[] = [
  {
    id: '1',
    user_id: 'dummy',
    created_at: '2026-04-14T10:00:00.000Z',
    title: 'パーソナルトレーナー向け料金提案ツール',
    raw_text: 'トレーナーが料金プランを簡単に作れるWebツール。顧客タイプに合わせた提案ができる。',
    summary: '個人トレーナーが料金プランを素早く作成・提案できるSaaS。顧客属性に合わせた自動提案が特徴。',
    tags: ['SaaS', 'フィットネス', '料金設計', 'B2B'],
    source_platform: 'Claude',
    human_note: null,
    intent: '商品化',
    related_project: 'TrainerDocs',
    priority_category: '今すぐ',
    time_slot: '今月',
    impact_score: 4,
    difficulty_score: 3,
    continuity_score: 4,
    placement_score: 5,
    mental_score: 4,
    revenue_score: 4,
    related_ids: ['2'],
  },
  {
    id: '2',
    user_id: 'dummy',
    created_at: '2026-04-11T09:00:00.000Z',
    title: 'AIが自動更新するポートフォリオサイト',
    raw_text: 'GitHubの活動やブログ記事を自動でポートフォリオに反映するサービス。',
    summary: 'GitHub/ブログ連携で自動更新されるポートフォリオ生成ツール。エンジニア向け放置型SaaS。',
    tags: ['ポートフォリオ', 'エンジニア', '自動化', '放置型'],
    source_platform: 'ChatGPT',
    human_note: '類似サービスは多いが差別化ポイントを考えたい',
    intent: '検討中',
    related_project: 'その他',
    priority_category: '仕込み',
    time_slot: '3ヶ月以内',
    impact_score: 3,
    difficulty_score: 2,
    continuity_score: 5,
    placement_score: 3,
    mental_score: 5,
    revenue_score: 3,
    related_ids: ['1'],
  },
  {
    id: '3',
    user_id: 'dummy',
    created_at: '2026-04-06T08:00:00.000Z',
    title: 'ノーコードLP生成ツール',
    raw_text: 'テキスト入力だけでLPを自動生成するツール。AIがコピーとデザインを両方やる。',
    summary: 'テキスト→ランディングページを自動生成。コピーもレイアウトもAIが担当するノーコードツール。',
    tags: ['ノーコード', 'LP', 'AI生成', 'マーケティング'],
    source_platform: 'Memo',
    human_note: null,
    intent: 'メモ',
    related_project: 'IdeaStock',
    priority_category: '挑戦',
    time_slot: '半年〜',
    impact_score: 5,
    difficulty_score: 4,
    continuity_score: 3,
    placement_score: 2,
    mental_score: 3,
    revenue_score: 5,
    related_ids: [],
  },
  {
    id: '4',
    user_id: 'dummy',
    created_at: '2026-04-02T07:00:00.000Z',
    title: 'メモ→ブログ記事自動変換ツール',
    raw_text: '走り書きメモをAIがブログ記事に整形してくれるツール。下書き→公開まで最小ステップ。',
    summary: '雑なメモを入力するだけで、ブログ記事のドラフトをAIが整形する。ライター・個人発信者向け。',
    tags: ['ライティング', 'ブログ', '自動化', '個人発信'],
    source_platform: 'Perplexity',
    human_note: 'IdeaStockと組み合わせると面白い',
    intent: '検討中',
    related_project: 'IdeaStock',
    priority_category: '仕込み',
    time_slot: '3ヶ月以内',
    impact_score: 3,
    difficulty_score: 2,
    continuity_score: 4,
    placement_score: 4,
    mental_score: 5,
    revenue_score: 2,
    related_ids: [],
  },
];
